"""
jarvis/core/orchestrator.py

Central coordinator for all JARVIS subsystems.

The Orchestrator owns the lifecycle of every major component and
routes each voice command through the full pipeline:

    SpeechRecognition → ConversationManager → Planner
    → ToolSelector → PermissionManager → ToolExecutor
    → ResponseGenerator → TextToSpeech

Design goals:   
    - Dependency injection over global state: every subsystem is
      passed into the constructor rather than imported and instantiated
      here. This makes each subsystem independently testable and
      prevents circular import chains.
    - Protocol-typed interfaces: downstream modules that are not yet
      written are represented as typing.Protocol definitions. The
      Orchestrator compiles and runs with any compliant implementation
      without needing to know the concrete class name.
    - Clean async lifecycle: start() initialises all subsystems in
      dependency order; stop() tears them down in reverse order with
      a configurable drain timeout so in-flight requests complete
      gracefully.
    - Single pipeline lock: only one voice command is processed at a
      time. A second wake-word trigger while a command is in-flight is
      queued (up to the queue depth limit) rather than dropped or
      processed concurrently, preventing interleaved LLM calls that
      would corrupt conversation history.

This module has no external dependencies beyond the Python standard
library and the other JARVIS modules that are passed in via injection.
"""

from __future__ import annotations

import asyncio
import logging
import time
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any, Optional, Protocol, runtime_checkable

from utils.config_loader import Settings

__all__ = [
    "OrchestratorError",
    "PipelineResult",
    "OrchestratorState",
    "Orchestrator",
]

logger = logging.getLogger("jarvis.core.orchestrator")


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class OrchestratorError(Exception):
    """Raised when the orchestrator cannot complete a pipeline request."""


# ---------------------------------------------------------------------------
# Pipeline result
# ---------------------------------------------------------------------------

@dataclass
class PipelineResult:
    """The outcome of processing a single user command through the pipeline.

    Attributes:
        user_input:      The transcribed user utterance.
        assistant_reply: The final text response generated by JARVIS.
        tool_calls:      List of tool identifiers that were invoked during
                         this turn, in order of execution.
        latency_ms:      Wall-clock time from pipeline entry to the first
                         character of the assistant reply, in milliseconds.
        success:         False if any stage of the pipeline failed.
        error:           Human-readable error description if success is False.
    """

    user_input: str
    assistant_reply: str
    tool_calls: list[str] = field(default_factory=list)
    latency_ms: float = 0.0
    success: bool = True
    error: Optional[str] = None


# ---------------------------------------------------------------------------
# Orchestrator lifecycle state
# ---------------------------------------------------------------------------

class OrchestratorState(Enum):
    """Operational state of the Orchestrator."""

    IDLE = auto()       # Constructed but not yet started
    STARTING = auto()   # start() is running
    RUNNING = auto()    # All subsystems initialised; ready for commands
    STOPPING = auto()   # stop() is running; draining the queue
    STOPPED = auto()    # Fully shut down


# ---------------------------------------------------------------------------
# Subsystem Protocols
#
# Each Protocol defines the minimum interface the Orchestrator requires
# from a subsystem. Concrete implementations (written in later files) must
# satisfy these contracts. Using Protocols instead of abstract base classes
# keeps the import graph acyclic — the Orchestrator does not need to import
# the concrete module, only the Protocol defined here.
# ---------------------------------------------------------------------------

@runtime_checkable
class ConversationManagerProtocol(Protocol):
    """Interface expected from core/conversation_manager.py."""

    async def process(self, user_input: str) -> str:
        """Process a user utterance and return the assistant reply."""
        ...

    def get_history(self) -> list[dict[str, str]]:
        """Return the current conversation history as a list of role/content dicts."""
        ...

    def clear(self) -> None:
        """Clear the current session's conversation history."""
        ...


@runtime_checkable
class TextToSpeechProtocol(Protocol):
    """Interface expected from audio/text_to_speech.py."""

    def speak(self, text: str) -> None:
        """Convert text to speech and play it."""
        ...

    def stop(self) -> None:
        """Stop any currently playing speech immediately."""
        ...


@runtime_checkable
class WakeWordProtocol(Protocol):
    """Interface expected from audio/wake_word.py."""

    def start_listening(self) -> None:
        """Begin listening for the wake word."""
        ...

    def stop_listening(self) -> None:
        """Stop the wake word listener."""
        ...


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------

class Orchestrator:
    """Coordinates all JARVIS subsystems through the command pipeline.

    Usage:
        settings = load_settings()
        permission_manager = PermissionManager(confirmation_callback=cb)
        conversation_manager = ConversationManager(settings, llm_client, ...)
        tts = TextToSpeechEngine(settings)

        orchestrator = Orchestrator(settings=settings)
        orchestrator.register_component("conversation_manager", conversation_manager)
        orchestrator.register_component("tts", tts)

        await orchestrator.start()
        result = await orchestrator.process_command("What time is it?")
        await orchestrator.stop()

    Component registration is order-independent. Components registered
    before start() are initialised during start(); components registered
    after start() are available immediately without re-initialisation.
    """

    #: Maximum number of commands that can be queued while a command is
    #: in-flight. Commands beyond this limit are rejected with an error
    #: rather than silently dropped.
    QUEUE_DEPTH: int = 4

    #: Seconds to wait for in-flight commands to complete during stop().
    DRAIN_TIMEOUT_SECONDS: float = 30.0

    def __init__(self, settings: Settings) -> None:
        """Initialise the Orchestrator.

        Args:
            settings: Fully loaded Settings object from config_loader.py.
                The Orchestrator passes relevant sub-configs to each
                subsystem during start().
        """
        self._settings = settings
        self._state = OrchestratorState.IDLE
        self._components: dict[str, Any] = {}

        # Asyncio primitives — created lazily in start() so the
        # constructor works outside an event loop.
        self._command_queue: Optional[asyncio.Queue[str]] = None
        self._pipeline_lock: Optional[asyncio.Lock] = None
        self._shutdown_event: Optional[asyncio.Event] = None
        self._worker_task: Optional[asyncio.Task[None]] = None

        # Metrics
        self._commands_processed: int = 0
        self._commands_failed: int = 0

        logger.info("Orchestrator initialised (state=IDLE)")

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def start(self) -> None:
        """Start the Orchestrator and all registered subsystems.

        Transitions through STARTING → RUNNING. Idempotent if called
        while already RUNNING.

        Raises:
            OrchestratorError: If start() is called while STOPPING or
                after the orchestrator has been STOPPED.
        """
        if self._state == OrchestratorState.RUNNING:
            logger.debug("Orchestrator.start() called but already RUNNING — no-op")
            return

        if self._state in (OrchestratorState.STOPPING, OrchestratorState.STOPPED):
            raise OrchestratorError(
                f"Cannot restart a stopped Orchestrator (state={self._state.name}). "
                "Create a new instance instead."
            )

        self._state = OrchestratorState.STARTING
        logger.info("Orchestrator starting — %d component(s) registered", len(self._components))

        # Initialise asyncio primitives inside the event loop.
        self._command_queue = asyncio.Queue(maxsize=self.QUEUE_DEPTH)
        self._pipeline_lock = asyncio.Lock()
        self._shutdown_event = asyncio.Event()

        # Start the background worker that drains the command queue.
        self._worker_task = asyncio.create_task(
            self._command_worker(), name="jarvis-pipeline-worker"
        )

        self._state = OrchestratorState.RUNNING
        logger.info("Orchestrator running — ready for commands")

    async def stop(self, drain_timeout: Optional[float] = None) -> None:
        """Stop the Orchestrator, allowing in-flight commands to finish.

        Args:
            drain_timeout: Seconds to wait for the queue to empty before
                forcing shutdown. Defaults to DRAIN_TIMEOUT_SECONDS.
        """
        if self._state not in (OrchestratorState.RUNNING, OrchestratorState.STARTING):
            logger.debug(
                "Orchestrator.stop() called but state is %s — no-op", self._state.name
            )
            return

        self._state = OrchestratorState.STOPPING
        timeout = drain_timeout if drain_timeout is not None else self.DRAIN_TIMEOUT_SECONDS
        logger.info(
            "Orchestrator stopping — draining queue (timeout=%.1fs)", timeout
        )

        # Signal the worker to exit after the queue empties.
        if self._shutdown_event:
            self._shutdown_event.set()

        # Wait for the worker to finish.
        if self._worker_task and not self._worker_task.done():
            try:
                await asyncio.wait_for(self._worker_task, timeout=timeout)
            except asyncio.TimeoutError:
                logger.warning(
                    "Pipeline worker did not finish within %.1fs; cancelling",
                    timeout,
                )
                self._worker_task.cancel()
                try:
                    await self._worker_task
                except asyncio.CancelledError:
                    pass

        # Stop the wake word listener if registered.
        wake_word = self._components.get("wake_word")
        if wake_word is not None and isinstance(wake_word, WakeWordProtocol):
            try:
                wake_word.stop_listening()
            except Exception:  # noqa: BLE001
                logger.exception("Error stopping wake word listener during shutdown")

        self._state = OrchestratorState.STOPPED
        logger.info(
            "Orchestrator stopped — processed=%d, failed=%d",
            self._commands_processed,
            self._commands_failed,
        )

    # ------------------------------------------------------------------
    # Command processing
    # ------------------------------------------------------------------

    async def process_command(self, user_input: str) -> PipelineResult:
        """Submit a command to the pipeline and wait for the result.

        This method is safe to call from any coroutine. It queues the
        command and blocks until the pipeline returns a result, so the
        caller does not need to manage the queue directly.

        Args:
            user_input: The transcribed user utterance.

        Returns:
            PipelineResult containing the assistant reply and metadata.

        Raises:
            OrchestratorError: If the Orchestrator is not in RUNNING state,
                or the command queue is full.
        """
        if self._state != OrchestratorState.RUNNING:
            raise OrchestratorError(
                f"Cannot process command: Orchestrator is {self._state.name}, "
                f"not RUNNING."
            )

        user_input = user_input.strip()
        if not user_input:
            return PipelineResult(
                user_input=user_input,
                assistant_reply="",
                success=False,
                error="Empty input — nothing to process.",
            )

        logger.debug("process_command received: %r", user_input[:120])

        # Run the pipeline directly (queue is for background wake-word flow;
        # direct callers get immediate synchronous execution under the lock).
        return await self._run_pipeline(user_input)

    async def enqueue_command(self, user_input: str) -> bool:
        """Non-blocking enqueue for the wake-word background flow.

        The wake word module calls this from its callback so it does not
        need to await the full pipeline result. The background worker
        picks up the command and calls TTS when done.

        Args:
            user_input: Transcribed utterance from speech recognition.

        Returns:
            True if the command was queued, False if the queue is full.
        """
        if self._state != OrchestratorState.RUNNING or self._command_queue is None:
            logger.warning("enqueue_command called but Orchestrator is not RUNNING")
            return False

        try:
            self._command_queue.put_nowait(user_input)
            logger.debug("Command queued (depth=%d)", self._command_queue.qsize())
            return True
        except asyncio.QueueFull:
            logger.warning(
                "Command queue full (depth=%d) — dropping: %r",
                self.QUEUE_DEPTH,
                user_input[:60],
            )
            return False

    # ------------------------------------------------------------------
    # Background worker
    # ------------------------------------------------------------------

    async def _command_worker(self) -> None:
        """Background task: drain the command queue and drive TTS output.

        Runs continuously until the shutdown event is set and the queue
        is empty. Each command is processed under the pipeline lock to
        guarantee serial execution and a consistent conversation history.
        """
        assert self._command_queue is not None
        assert self._shutdown_event is not None

        while True:
            # Wait for a command or shutdown signal.
            try:
                user_input = await asyncio.wait_for(
                    self._command_queue.get(), timeout=0.2
                )
            except asyncio.TimeoutError:
                # Check whether shutdown was requested while the queue
                # was empty — the normal exit path.
                if self._shutdown_event.is_set() and self._command_queue.empty():
                    logger.debug("Pipeline worker: queue empty and shutdown set — exiting")
                    return
                continue

            try:
                result = await self._run_pipeline(user_input)
                self._speak_result(result)
            except Exception:  # noqa: BLE001
                logger.exception(
                    "Unhandled exception in pipeline worker for input %r",
                    user_input[:80],
                )
            finally:
                self._command_queue.task_done()

    # ------------------------------------------------------------------
    # Core pipeline
    # ------------------------------------------------------------------

    async def _run_pipeline(self, user_input: str) -> PipelineResult:
        """Execute the full processing pipeline for one user utterance.

        Acquires the pipeline lock so only one command runs at a time.
        Delegates to the ConversationManager for actual LLM reasoning.
        If no ConversationManager is registered (subsystems not yet
        built), falls back to a diagnostic error reply.

        Args:
            user_input: The transcribed user utterance.

        Returns:
            PipelineResult with all pipeline metadata populated.
        """
        assert self._pipeline_lock is not None

        async with self._pipeline_lock:
            start_time = time.monotonic()

            conversation_manager: Optional[ConversationManagerProtocol] = (
                self._components.get("conversation_manager")  # type: ignore[assignment]
            )

            if conversation_manager is None:
                # No conversation manager registered yet — return a
                # diagnostic reply so the system doesn't silently fail.
                logger.warning(
                    "No conversation_manager registered — cannot process: %r",
                    user_input[:80],
                )
                return PipelineResult(
                    user_input=user_input,
                    assistant_reply=(
                        "I am not fully initialised yet. "
                        "The conversation manager is not registered."
                    ),
                    success=False,
                    error="conversation_manager not registered",
                    latency_ms=(time.monotonic() - start_time) * 1000,
                )

            try:
                assistant_reply = await conversation_manager.process(user_input)
                latency_ms = (time.monotonic() - start_time) * 1000
                self._commands_processed += 1

                logger.info(
                    "Pipeline completed in %.0fms — input=%r reply=%r",
                    latency_ms,
                    user_input[:60],
                    assistant_reply[:60],
                )

                return PipelineResult(
                    user_input=user_input,
                    assistant_reply=assistant_reply,
                    latency_ms=latency_ms,
                    success=True,
                )

            except Exception as exc:  # noqa: BLE001
                latency_ms = (time.monotonic() - start_time) * 1000
                self._commands_failed += 1
                error_msg = f"Pipeline error: {exc}"
                logger.exception(
                    "Pipeline failed after %.0fms for input %r",
                    latency_ms,
                    user_input[:80],
                )
                return PipelineResult(
                    user_input=user_input,
                    assistant_reply=(
                        "I encountered an error processing that request. "
                        "Please try again."
                    ),
                    latency_ms=latency_ms,
                    success=False,
                    error=error_msg,
                )

    # ------------------------------------------------------------------
    # TTS output
    # ------------------------------------------------------------------

    def _speak_result(self, result: PipelineResult) -> None:
        """Send the assistant reply to the TTS engine, if one is registered.

        Silently skips TTS if no engine is registered (e.g. during tests
        or when running in text-only mode).

        Args:
            result: The PipelineResult whose assistant_reply to speak.
        """
        if not result.assistant_reply:
            return

        tts: Optional[TextToSpeechProtocol] = self._components.get("tts")  # type: ignore[assignment]
        if tts is None:
            return

        try:
            tts.speak(result.assistant_reply)
        except Exception:  # noqa: BLE001
            logger.exception("TTS engine raised an exception during speak()")

    # ------------------------------------------------------------------
    # Component registry
    # ------------------------------------------------------------------

    def register_component(self, name: str, component: Any) -> None:
        """Register a subsystem component by name.

        Named components are retrieved by the pipeline stages that need
        them. Standard names used internally:
            "conversation_manager"  -- ConversationManagerProtocol
            "tts"                   -- TextToSpeechProtocol
            "wake_word"             -- WakeWordProtocol
            "permission_manager"    -- PermissionManager

        Additional components (tools, browser, etc.) can be registered
        under any name for retrieval by downstream pipeline stages.

        Args:
            name:      Unique identifier for this component.
            component: The component instance. No interface validation
                       is performed here; Protocol compliance is checked
                       by the pipeline stage that consumes the component.
        """
        previous = self._components.get(name)
        self._components[name] = component

        if previous is not None:
            logger.info(
                "Component %r replaced (old=%s, new=%s)",
                name,
                type(previous).__name__,
                type(component).__name__,
            )
        else:
            logger.debug(
                "Component registered: %r (%s)", name, type(component).__name__
            )

    def get_component(self, name: str) -> Optional[Any]:
        """Retrieve a registered component by name.

        Args:
            name: The name passed to register_component().

        Returns:
            The component instance, or None if not registered.
        """
        return self._components.get(name)

    # ------------------------------------------------------------------
    # Diagnostics
    # ------------------------------------------------------------------

    @property
    def state(self) -> OrchestratorState:
        """Current lifecycle state of the Orchestrator."""
        return self._state

    @property
    def is_running(self) -> bool:
        """True if the Orchestrator is in RUNNING state."""
        return self._state == OrchestratorState.RUNNING

    def get_metrics(self) -> dict[str, Any]:
        """Return a snapshot of runtime metrics.

        Returns:
            Dict containing:
                state:               Current OrchestratorState name.
                commands_processed:  Total commands completed successfully.
                commands_failed:     Total commands that raised an exception.
                queue_depth:         Current number of queued commands.
                registered_components: Names of all registered components.
        """
        return {
            "state": self._state.name,
            "commands_processed": self._commands_processed,
            "commands_failed": self._commands_failed,
            "queue_depth": (
                self._command_queue.qsize() if self._command_queue else 0
            ),
            "registered_components": list(self._components.keys()),
        }